const element = {
    a: ['download', 'href', 'hreflang', 'media', 'ping', 'referrerpolicy', 'rel', 'target', 'type'],
    abbr: ['class', 'dir', 'lang', 'style', 'title'],
    address: ['class', 'dir', 'lang', 'style'],
    area: ['alt', 'coords', 'download', 'href', 'hreflang', 'media', 'rel', 'shape', 'target'],
    article: ['class', 'dir', 'lang', 'style'],
    aside: ['class', 'dir', 'lang', 'style'],
    audio: ['autoplay', 'controls', 'crossorigin', 'loop', 'muted', 'preload', 'src'],
    b: ['class', 'dir', 'lang', 'style'],
    base: ['href', 'target'],
    bdi: ['dir'],
    bdo: ['dir'],
    blockquote: ['cite', 'class', 'dir', 'lang', 'style'],
    body: ['class', 'dir', 'lang', 'style'],
    br: [],
    button: ['autofocus', 'disabled', 'form', 'formaction', 'formenctype', 'formmethod', 'formnovalidate', 'formtarget', 'name', 'type', 'value'],
    canvas: ['height', 'width'],
    caption: ['class', 'dir', 'lang', 'style'],
    cite: ['class', 'dir', 'lang', 'style'],
    code: ['class', 'dir', 'lang', 'style'],
    col: ['span'],
    colgroup: ['span'],
    data: ['value'],
    datalist: ['class', 'dir', 'lang', 'style'],
    dd: ['class', 'dir', 'lang', 'style'],
    del: ['cite', 'datetime'],
    details: ['open'],
    dfn: ['class', 'dir', 'lang', 'style', 'title'],
    dialog: ['open'],
    div: ['class', 'dir', 'lang', 'style'],
    dl: ['class', 'dir', 'lang', 'style'],
    dt: ['class', 'dir', 'lang', 'style'],
    em: ['class', 'dir', 'lang', 'style'],
    embed: ['height', 'src', 'type', 'width'],
    fieldset: ['class', 'dir', 'disabled', 'form', 'name'],
    figcaption: ['class', 'dir', 'lang', 'style'],
    figure: ['class', 'dir', 'lang', 'style'],
    footer: ['class', 'dir', 'lang', 'style'],
    form: ['accept-charset', 'action', 'autocomplete', 'enctype', 'method', 'name', 'novalidate', 'target'],
    h1: ['align', 'class', 'dir', 'lang', 'style'],
    h2: ['align', 'class', 'dir', 'lang', 'style'],
    h3: ['align', 'class', 'dir', 'lang', 'style'],
    h4: ['align', 'class', 'dir', 'lang', 'style'],
    h5: ['align', 'class', 'dir', 'lang', 'style'],
    h6: ['align', 'class', 'dir', 'lang', 'style'],
    head: ['profile'],
    header: ['class', 'dir', 'lang', 'style'],
    hgroup: ['class', 'dir', 'lang', 'style'],
    hr: ['align', 'class', 'dir', 'lang', 'style'],
    html: ['dir', 'lang'],
    i: ['class', 'dir', 'lang', 'style'],
    iframe: ['allowfullscreen', 'height', 'sandbox', 'src', 'width'],
    img: ['align', 'alt', 'border', 'class', 'height', 'hspace', 'id', 'src', 'width'],
    input: ['accept', 'alt', 'autocomplete', 'autofocus', 'checked', 'disabled', 'form', 'formaction', 'formenctype', 'formmethod', 'formnovalidate', 'formtarget', 'height', 'list', 'max', 'maxlength', 'min', 'multiple', 'name', 'pattern', 'placeholder', 'readonly', 'required', 'size', 'src', 'step', 'type', 'value', 'width'],
    ins: ['cite', 'datetime'],
    kbd: ['class', 'dir', 'lang', 'style'],
    label: ['for', 'form'],
    legend: ['accesskey', 'class', 'dir', 'lang', 'style'],
    li: ['class', 'dir', 'lang', 'style', 'value'],
    link: ['as', 'crossorigin', 'href', 'hreflang', 'imagesizes', 'imagesrcset', 'integrity', 'media', 'referrerpolicy', 'rel', 'sizes', 'type'],
    main: ['class', 'dir', 'lang', 'style'],
    map: ['name'],
    mark: ['class', 'dir', 'lang', 'style'],
    meta: ['charset', 'content', 'http-equiv', 'name'],
    meter: ['class', 'dir', 'high', 'lang', 'low', 'max', 'min', 'optimum', 'value'],
    nav: ['class', 'dir', 'lang', 'style'],
    noscript: [],
    object: ['class', 'data', 'form', 'height', 'name', 'type', 'usemap', 'width'],
    ol: ['class', 'dir', 'lang', 'reversed', 'start', 'style', 'type'],
    optgroup: ['class', 'dir', 'disabled', 'label'],
    option: ['class', 'dir', 'disabled', 'label', 'selected', 'value'],
    output: ['for', 'form', 'name'],
    p: ['align', 'class', 'dir', 'style', 'id'],
    param: ['name', 'value'],
    picture: [],
    pre: ['class', 'dir', 'lang', 'style', 'width'],
    progress: ['class', 'dir', 'lang', 'max', 'style', 'value'],
    q: ['cite', 'class', 'dir', 'lang', 'style'],
    rp: ['class', 'dir', 'lang', 'style'],
    rt: ['class', 'dir', 'lang', 'style'],
    ruby: ['class', 'dir', 'lang', 'style'],
    s: ['class', 'dir', 'lang', 'style'],
    samp: ['class', 'dir', 'lang', 'style'],
    script: ['async', 'charset', 'defer', 'integrity', 'language', 'src', 'type'],
    section: ['class', 'dir', 'lang', 'style'],
    select: ['autofocus', 'class', 'dir', 'disabled', 'form', 'multiple', 'name', 'required', 'size'],
    slot: ['name'],
    small: ['class', 'dir', 'lang', 'style'],
    source: ['media', 'sizes', 'src', 'srcset', 'type'],
    span: ['class', 'id', 'style'],
    strong: ['class', 'dir', 'lang', 'style'],
    style: ['media', 'nonce', 'title', 'type'],
    sub: ['class', 'dir', 'lang', 'style'],
    summary: [],
    sup: ['class', 'dir', 'lang', 'style'],
    table: ['border', 'class', 'dir', 'lang', 'style', 'width'],
    tbody: ['align', 'char', 'charoff', 'class', 'dir', 'lang', 'style', 'valign'],
    td: ['abbr', 'align', 'axis', 'background', 'bgcolor', 'char', 'charoff', 'class', 'colspan', 'dir', 'headers', 'height', 'lang', 'rowspan', 'scope', 'style', 'valign', 'width'],
    template: [],
    textarea: ['autofocus', 'class', 'cols', 'dir', 'disabled', 'form', 'maxlength', 'minlength', 'name', 'placeholder', 'readonly', 'required', 'rows', 'wrap'],
    tfoot: ['align', 'char', 'charoff', 'class', 'dir', 'lang', 'style', 'valign'],
    th: ['abbr', 'align', 'axis', 'background', 'bgcolor', 'char', 'charoff', 'class', 'colspan', 'dir', 'headers', 'height', 'lang', 'rowspan', 'scope', 'style', 'valign', 'width'],
    thead: ['align', 'char', 'charoff', 'class', 'dir', 'lang', 'style', 'valign'],
    time: ['class', 'datetime', 'dir', 'lang', 'style'],
    title: [],
    tr: ['align', 'bgcolor', 'char', 'charoff', 'class', 'dir', 'lang', 'style', 'valign'],
    track: ['default', 'kind', 'label', 'src', 'srclang'],
    u: ['class', 'dir', 'lang', 'style'],
    ul: ['class', 'dir', 'lang', 'style', 'type'],
    var: ['class', 'dir', 'lang', 'style'],
    video: ['autoplay', 'controls', 'crossorigin', 'height', 'loop', 'muted', 'poster', 'preload', 'src', 'width'],
    wbr: []
};


const cssProperties = {
    alignContent: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'stretch'],
    alignItems: ['flex-start', 'flex-end', 'center', 'baseline', 'stretch'],
    alignSelf: ['auto', 'flex-start', 'flex-end', 'center', 'baseline', 'stretch'],
    animation: ['animation-name', 'animation-duration', 'animation-timing-function', 'animation-delay', 'animation-iteration-count', 'animation-direction', 'animation-fill-mode', 'animation-play-state'],
    animationName: ['none'],
    animationDuration: ['<time>', '0s'],
    animationTimingFunction: ['ease', 'linear', 'ease-in', 'ease-out', 'ease-in-out'],
    animationDelay: ['<time>', '0s'],
    animationIterationCount: ['infinite', '<number>'],
    animationDirection: ['normal', 'reverse', 'alternate', 'alternate-reverse'],
    animationFillMode: ['none', 'forwards', 'backwards', 'both'],
    animationPlayState: ['running', 'paused'],
    backfaceVisibility: ['visible', 'hidden'],
    background: ['background-color', 'background-image', 'background-repeat', 'background-position', 'background-size', 'background-attachment'],
    backgroundColor: ['<color>', 'transparent'],
    backgroundImage: ['none'],
    backgroundRepeat: ['repeat', 'repeat-x', 'repeat-y', 'no-repeat'],
    backgroundPosition: ['center', 'top', 'right', 'bottom', 'left'],
    backgroundSize: ['auto', 'cover', 'contain'],
    backgroundAttachment: ['scroll', 'fixed'],
    border: ['border-width', 'border-style', 'border-color'],
    borderWidth: ['<length>', 'thin', 'medium', 'thick'],
    borderStyle: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
    borderColor: ['<color>', 'transparent'],
    borderRadius: ['<length>', '<percentage>', '50%'],
    boxShadow: ['none'],
    boxSizing: ['content-box', 'border-box'],
    clear: ['none', 'left', 'right', 'both'],
    clip: ['<shape>', 'auto'],
    color: ['<color>'],
    columnCount: ['<integer>', 'auto'],
    columnGap: ['<length>', 'normal'],
    columnRule: ['column-rule-width', 'column-rule-style', 'column-rule-color'],
    columnRuleWidth: ['<length>', 'thin', 'medium', 'thick'],
    columnRuleStyle: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
    columnRuleColor: ['<color>'],
    columns: ['column-width', 'column-count'],
    columnWidth: ['<length>', 'auto'],
    content: ['<string>', 'open-quote', 'close-quote', 'no-open-quote', 'no-close-quote'],
    cursor: ['auto', 'default', 'pointer', 'wait', 'text', 'move', 'not-allowed', 'crosshair', 'help', 'progress'],
    display: ['block', 'inline', 'inline-block', 'inline-table', 'flex', 'grid', 'table', 'table-cell', 'table-row'],
    filter: ['none'],
    flex: ['flex-grow', 'flex-shrink', 'flex-basis'],
    flexGrow: ['<number>', '0'],
    flexShrink: ['<number>', '1'],
    flexBasis: ['<length>', 'auto'],
    float: ['none', 'left', 'right'],
    fontFamily: ['<family-name>', 'serif', 'sans-serif', 'monospace'],
    fontSize: ['<length>', '<percentage>'],
    fontStyle: ['normal', 'italic', 'oblique'],
    fontWeight: ['normal', 'bold', 'bolder', 'lighter', '<number>'],
    height: ['<length>', '<percentage>', 'auto'],
    justifyContent: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around'],
    left: ['<length>', '<percentage>', 'auto'],
    letterSpacing: ['normal', '<length>'],
    lineHeight: ['normal', '<number>', '<length>', '<percentage>'],
    listStyle: ['list-style-type', 'list-style-position', 'list-style-image'],
    listStyleType: ['disc', 'circle', 'square', 'decimal', 'lower-roman', 'upper-roman', 'lower-alpha', 'upper-alpha', 'none'],
    listStylePosition: ['inside', 'outside'],
    listStyleImage: ['none'],
    margin: ['<length>', '<percentage>', 'auto'],
    marginBottom: ['<length>', '<percentage>', 'auto'],
    marginLeft: ['<length>', '<percentage>', 'auto'],
    marginRight: ['<length>', '<percentage>', 'auto'],
    marginTop: ['<length>', '<percentage>', 'auto'],
    maxHeight: ['<length>', '<percentage>', 'none'],
    maxWidth: ['<length>', '<percentage>', 'none'],
    minHeight: ['<length>', '<percentage>'],
    minWidth: ['<length>', '<percentage>'],
    opacity: ['<number>'],
    order: ['<integer>'],
    outline: ['outline-width', 'outline-style', 'outline-color'],
    outlineWidth: ['<length>', 'thin', 'medium', 'thick'],
    outlineStyle: ['none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
    outlineColor: ['<color>', 'invert'],
    overflow: ['visible', 'hidden', 'scroll', 'auto'],
    overflowX: ['visible', 'hidden', 'scroll', 'auto'],
    overflowY: ['visible', 'hidden', 'scroll', 'auto'],
    padding: ['<length>', '<percentage>'],
    paddingBottom: ['<length>', '<percentage>'],
    paddingLeft: ['<length>', '<percentage>'],
    paddingRight: ['<length>', '<percentage>'],
    paddingTop: ['<length>', '<percentage>'],
    position: ['static', 'relative', 'absolute', 'fixed', 'sticky'],
    right: ['<length>', '<percentage>', 'auto'],
    textAlign: ['left', 'right', 'center', 'justify'],
    textDecoration: ['text-decoration-line', 'text-decoration-style', 'text-decoration-color'],
    textDecorationLine: ['none', 'underline', 'overline', 'line-through'],
    textDecorationStyle: ['solid', 'double', 'dotted', 'dashed', 'wavy'],
    textDecorationColor: ['<color>'],
    textTransform: ['none', 'capitalize', 'uppercase', 'lowercase'],
    top: ['<length>', '<percentage>', 'auto'],
    transform: ['none'],
    transformOrigin: ['<length>', '<percentage>'],
    transition: ['transition-property', 'transition-duration', 'transition-timing-function', 'transition-delay'],
    transitionProperty: ['none', 'all', 'property-name'],
    transitionDuration: ['<time>', '0s'],
    transitionTimingFunction: ['ease', 'linear', 'ease-in', 'ease-out', 'ease-in-out'],
    transitionDelay: ['<time>', '0s'],
    visibility: ['visible', 'hidden', 'collapse'],
    whiteSpace: ['normal', 'nowrap', 'pre', 'pre-wrap', 'pre-line'],
    width: ['<length>', '<percentage>', 'auto'],
    wordBreak: ['normal', 'break-all', 'keep-all', 'break-word'],
    wordWrap: ['normal', 'break-word'],
    zIndex: ['auto', '<integer>'],
};

const htmlTagsByCategory = {
    structurel: ["header", "main", "nav", "section", "article", "aside", "footer", "h1", "h2", "h3", "h4", "h5", "h6", "p", "ul", "ol", "li", "dl", "dt", "dd", "blockquote", "pre", "hr", "br", "div"],
    text: ["span", "a", "strong", "em", "abbr", "del", "ins", "sub", "sup", "code", "kbd", "samp", "var", "mark", "q", "cite"],
    media: ["img", "audio", "video", "iframe", "object", "embed", "param", "canvas", "source", "track"],
    form: ["form", "input", "textarea", "select", "option", "optgroup", "button", "label", "fieldset", "legend", "datalist", "keygen", "output", "progress", "meter", "details", "summary"],
    table: ["table", "caption", "thead", "tbody", "tfoot", "tr", "th", "td"],
    semantique: ["mark", "time", "address", "abbr", "blockquote", "cite", "dfn", "var", "samp", "kbd", "sub", "sup", "small", "i", "b", "u", "s", "strong", "em"]
};

const cssPropertiesByCategory = {
    structurel: [
        "display",
        "padding",
        "margin",
        "background",
        "border",
        "width",
        "height",
        "color",
        "font-size",
        "text-align"
    ],
    text: [
        "color",
        "font-size",
        "font-weight",
        "text-decoration",
        "text-align",
        "text-transform",
        "line-height"
    ],
    multimedia: [
        "width",
        "height",
        "margin",
        "padding",
        "float",
        "position",
        "top",
        "left",
        "right",
        "bottom"
    ],
    form: [
        "width",
        "height",
        "margin",
        "padding",
        "display",
        "position",
        "top",
        "left",
        "right",
        "bottom"
    ],
    table: [
        "border",
        "border-collapse",
        "width",
        "height",
        "padding",
        "margin",
        "text-align",
        "vertical-align"
    ],
    semantique: [
        "color",
        "font-size",
        "font-weight",
        "text-decoration",
        "text-align",
        "text-transform",
        "line-height"
    ]
};


const cssSpecificByCategory = {
    structurel: {
        tags: ["header", "main", "nav", "section", "article", "aside", "footer", "h1", "h2", "h3", "h4", "h5", "h6", "p", "ul", "ol", "li", "dl", "dt", "dd", "blockquote", "pre", "hr", "br", "div"],
        attributes: {

        },
    },
    text: {
        tags: ["span", "a", "strong", "em", "abbr", "del", "ins", "sub", "sup", "code", "kbd", "samp", "var", "mark", "q", "cite"],
        attributes: {
            a: ["href", "target", "rel"],
            abbr: ["title"],
            q: ["cite"],
        },
    },
    multimedia: {
        tags: ["img", "audio", "video", "iframe", "object", "embed", "param", "canvas", "source", "track"],
        attributes: {
            img: ["src", "alt", "width", "height"],
            audio: ["src", "controls"],
            video: ["src", "controls"],
            iframe: ["src", "width", "height"],
            object: ["data", "type", "width", "height"],
        },
    },
    form: {
        tags: ["form", "input", "textarea", "select", "option", "optgroup", "button", "label", "fieldset", "legend", "datalist", "keygen", "output", "progress", "meter", "details", "summary"],
        attributes: {
            input: ["type", "name", "value", "placeholder", "disabled", "required"],
            textarea: ["name", "placeholder", "rows", "cols", "disabled", "required"],
            select: ["name", "disabled", "required"],
            option: ["value", "selected", "disabled"],
            button: ["type", "name", "value", "disabled"],
        },
    },
    table: {
        tags: ["table", "caption", "thead", "tbody", "tfoot", "tr", "th", "td"],
        attributes: {
            table: ["border", "cellspacing", "cellpadding"],
            th: ["colspan", "rowspan", "headers", "scope"],
            td: ["colspan", "rowspan", "headers"],
        },
    },
    semantique: {
        tags: ["mark", "time", "address", "abbr", "blockquote", "cite", "dfn", "var", "samp", "kbd", "sub", "sup", "small", "i", "b", "u", "s", "strong", "em"],
        attributes: {

        },
    },
};

const attributeValues = {
    align: ['left', 'center', 'right', 'justify'],
    alt: 'text',
    class: 'classname',
    dir: ['ltr', 'rtl', 'auto'],
    style: 'styles',
    id: 'identifier',
    href: 'URL',
    target: ['_blank', '_self', '_parent', '_top'],
    rel: ['alternate', 'author', 'bookmark', 'external', 'help', 'license', 'next', 'nofollow', 'noreferrer', 'noopener', 'prev', 'search', 'tag'],
    title: 'text',
    cite: 'URL',
    type: ['text', 'password', 'checkbox', 'radio', 'submit', 'reset', 'file', 'hidden', 'button', 'number', 'date', 'email', 'url', 'range', 'color', 'search'],
    name: 'name',
    value: 'value',
    placeholder: 'text',
    disabled: ['disabled'],
    required: ['required'],
    rows: 'number',
    cols: 'number',
    cellpadding: 'number',
    cellspacing: 'number',
    colspan: 'number',
    rowspan: 'number',
    headers: 'ids',
    scope: ['row', 'col', 'rowgroup', 'colgroup'],
    border: 'number',
    cellspacing: 'number',
    cellpadding: 'number',
    objectFit: ['fill', 'contain', 'cover', 'none', 'scale-down'],
    objectPosition: ['left', 'center', 'right', 'top', 'bottom'],
    animationName: 'name',
    animationDuration: 'time',
    animationTimingFunction: ['ease', 'linear', 'ease-in', 'ease-out', 'ease-in-out'],
    animationDelay: 'time',
    animationIterationCount: ['infinite', 'number'],
    animationDirection: ['normal', 'reverse', 'alternate', 'alternate-reverse'],
    animationFillMode: ['none', 'forwards', 'backwards', 'both'],
    animationPlayState: ['running', 'paused'],
    fontFamily: 'fontname',
    fontWeight: ['normal', 'bold', 'bolder', 'lighter', '100', '200', '300', '400', '500', '600', '700', '800', '900'],
    textTransform: ['none', 'capitalize', 'uppercase', 'lowercase'],
    textDecoration: ['none', 'underline', 'overline', 'line-through'],
    textShadow: 'x-offset y-offset blur-radius color',
    boxShadow: 'x-offset y-offset blur-radius spread-radius color',
};

const tagChildrenPossibilities = {
    "div": {
        "attributes": ["class", "id", "style"],
        "children": "any"
    },
    "p": {
        "attributes": ["align", "class", "dir", "style", "id"],
        "children": ["a", "abbr", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "data", "del", "dfn", "em", "embed", "i", "iframe", "img", "input", "ins", "kbd", "label", "map", "mark", "meter", "noscript", "object", "output", "picture", "q", "ruby", "s", "samp", "select", "small", "span", "strong", "sub", "sup", "svg", "textarea", "time", "u", "var", "video", "wbr", "#text"]
    },
    "span": {
        "attributes": ["class", "id", "style"],
        "children": ["a", "abbr", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "data", "del", "dfn", "em", "embed", "i", "iframe", "img", "input", "ins", "kbd", "label", "map", "mark", "meter", "noscript", "object", "output", "picture", "q", "ruby", "s", "samp", "select", "small", "span", "strong", "sub", "sup", "svg", "textarea", "time", "u", "var", "video", "wbr", "#text"]
    },
    "h1": {
        "attributes": ["align", "class", "dir", "style", "id"],
        "children": ["a", "abbr", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "data", "del", "dfn", "em", "embed", "i", "iframe", "img", "input", "ins", "kbd", "label", "map", "mark", "meter", "noscript", "object", "output", "picture", "q", "ruby", "s", "samp", "select", "small", "span", "strong", "sub", "sup", "svg", "textarea", "time", "u", "var", "video", "wbr", "#text"]
    },
    "h2": {
        "attributes": ["align", "class", "dir", "style", "id"],
        "children": ["a", "abbr", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "data", "del", "dfn", "em", "embed", "i", "iframe", "img", "input", "ins", "kbd", "label", "map", "mark", "meter", "noscript", "object", "output", "picture", "q", "ruby", "s", "samp", "select", "small", "span", "strong", "sub", "sup", "svg", "textarea", "time", "u", "var", "video", "wbr", "#text"]
    },
    "h3": {
        "attributes": ["align", "class", "dir", "style", "id"],
        "children": ["a", "abbr", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "data", "del", "dfn", "em", "embed", "i", "iframe", "img", "input", "ins", "kbd", "label", "map", "mark", "meter", "noscript", "object", "output", "picture", "q", "ruby", "s", "samp", "select", "small", "span", "strong", "sub", "sup", "svg", "textarea", "time", "u", "var", "video", "wbr", "#text"]
    },
    "img": {
        "attributes": ["align", "border", "class", "height", "hspace", "id"],
        "children": []
    },
    "a": {
        "attributes": ["class", "id", "style", "href", "target", "rel"],
        "children": ["#text", "abbr", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "data", "del", "dfn", "em", "embed", "i", "iframe", "img", "input", "ins", "kbd", "label", "map", "mark", "meter", "noscript", "object", "output", "picture", "q", "ruby", "s", "samp", "select", "small", "span", "strong", "sub", "sup", "svg", "textarea", "time", "u", "var", "video", "wbr"]
    },
    "ul": {
        "attributes": ["type", "class", "id", "style"],
        "children": ["li"]
    },
    "ol": {
        "attributes": ["type", "class", "id", "style"],
        "children": ["li"]
    },
    "li": {
        "attributes": ["value", "class", "id", "style"],
        "children": ["a", "abbr", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "data", "del", "dfn", "em", "embed", "i", "iframe", "img", "input", "ins", "kbd", "label", "map", "mark", "meter", "noscript", "object", "output", "picture", "q", "ruby", "s", "samp", "select", "small", "span", "strong", "sub", "sup", "svg", "textarea", "time", "u", "var", "video", "wbr", "#text"]
    },
    "table": {
        "attributes": ["border", "cellpadding", "cellspacing", "class", "id", "style"],
        "children": ["caption", "thead", "tbody", "tfoot", "tr"]
    },
    "thead": {
        "attributes": ["class", "id", "style"],
        "children": ["tr"]
    },
    "tbody": {
        "attributes": ["class", "id", "style"],
        "children": ["tr"]
    },
    "tfoot": {
        "attributes": ["class", "id", "style"],
        "children": ["tr"]
    },
    "tr": {
        "attributes": ["align", "class", "dir", "style", "id"],
        "children": ["th", "td"]
    },
    "th": {
        "attributes": ["abbr", "axis", "headers", "scope", "rowspan", "colspan", "align", "valign", "class", "id", "style"],
        "children": ["a", "abbr", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "data", "del", "dfn", "em", "embed", "i", "iframe", "img", "input", "ins", "kbd", "label", "map", "mark", "meter", "noscript", "object", "output", "picture", "q", "ruby", "s", "samp", "select", "small", "span", "strong", "sub", "sup", "svg", "textarea", "time", "u", "var", "video", "wbr", "#text"]
    },
    "td": {
        "attributes": ["headers", "scope", "rowspan", "colspan", "align", "valign", "class", "id", "style"],
        "children": ["a", "abbr", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "data", "del", "dfn", "em", "embed", "i", "iframe", "img", "input", "ins", "kbd", "label", "map", "mark", "meter", "noscript", "object", "output", "picture", "q", "ruby", "s", "samp", "select", "small", "span", "strong", "sub", "sup", "svg", "textarea", "time", "u", "var", "video", "wbr", "#text"]
    }
}
